apiVersion: v1
kind: Pod
metadata:
  name: env-pod
  labels:
    app: envpod
    env: dev
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello i am from env container; sleep 5; done"]
      env:
      - name: myname
        value: sunil  