apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wp-pvc
  namespace: practice
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "" 
  volumeMode: Filesystem    
  volumeName: wp-pv      