apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: practice
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

