# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   #namespace: game-2048
#   name: ingress-2048
#   annotations:
#     alb.ingress.kubernetes.io/ip-address-type: dualstack
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
# spec:
#   ingressClassName: alb
#   rules:
#     - http:
#         paths:
#         - path: /dino
#           pathType: Prefix
#           backend:
#             service:
#               name: dino
#               port:
#                 number: 80

        # - path: /nginx
        #   pathType: Prefix
        #   backend:
        #     service:
        #       name: webserversvc
        #       port:
        #         number: 80


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  annotations:    
    #kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"             # ** enabling path based routing 
    #ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dino
            port:
              number: 80

      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: webserversvc
            port:
              number: 80
        
      - path: /green
        pathType: Prefix
        backend:
          service:
            name: greenwebserver
            port:
              number: 80