apiVersion: v1
kind: Service
metadata:
  #namespace: game-2048
  name: dino
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: app-2048
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: webserversvc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: webserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: greenwebserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: greenwebserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP