apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
  namespace: practice
spec:
  containers: 
    - name: tomcatcont
      image: tomcat:8.0
      ports:
        - name: tomcat-port
          containerPort: 7500
      imagePullPolicy: Always
      volumeMounts:
        - name: cmvol
          mountPath: "/data"
          readOnly: true  

  volumes:
    - name: cmvol
      configMap:
        name: envcm
        items:
          - key: password4
            path: "forthpass"
          - key: password3
            path: "thirdpass"


