apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: pod

      #####################  CUSTOM ######################

      - job_name: 'buds-backend-cms'
        static_configs:
          - targets: ['10.3.12.229:1011']
            labels:
              namespace: 'prod'
        metrics_path: '/cms/metrics'

      - job_name: 'buds-backend-core'
        static_configs:
          - targets: ['10.3.1.79:3002']
            labels:
              namespace: 'prod'
        metrics_path: '/buds-portal/metrics'

      - job_name: 'buds-backend-uam'
        static_configs:
          - targets: ['10.3.10.65:1010']
            labels:
              namespace: 'prod'
        metrics_path: '/api/v1/metrics'

      - job_name: 'buds-bff'
        static_configs:
          - targets: ['10.3.5.137:3000']
            labels:
              namespace: 'prod'
        metrics_path: '/api/v1/metrics'      


     ########### CUSTOM ######################

      # - job_name: 'buds-backend-cms'
      #   kubernetes_sd_configs:
      #     - role: pod
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_label_app]
      #       action: keep
      #       regex: buds-backend-cms
      #     - source_labels: [__meta_kubernetes_namespace]
      #       action: keep
      #       regex: pre-prod
      #     - source_labels: [__meta_kubernetes_pod_container_port_number]
      #       action: keep
      #       regex: 1011  # Adjust this to match your actual metrics port name if needed
      #   metrics_path: '/cms/metrics'

      # - job_name: 'buds-backend-core'
      #   kubernetes_sd_configs:
      #     - role: pod
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_label_app]
      #       action: keep
      #       regex: buds-backend-core
      #     - source_labels: [__meta_kubernetes_namespace]
      #       action: keep
      #       regex: pre-prod
      #     - source_labels: [__meta_kubernetes_pod_container_port_number]
      #       action: keep
      #       regex: 3002  # Adjust this to match your actual metrics port name if needed
      #   metrics_path: '/buds-portal/metrics'

      # - job_name: 'buds-backend-uam'
      #   kubernetes_sd_configs:
      #     - role: pod
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_label_app]
      #       action: keep
      #       regex: buds-backend-uam
      #     - source_labels: [__meta_kubernetes_namespace]
      #       action: keep
      #       regex: pre-prod
      #     - source_labels: [__meta_kubernetes_pod_container_port_number]
      #       action: keep
      #       regex: 1010  # Adjust this to match your actual metrics port name if needed
      #   metrics_path: '/api/v1/metrics'

      # - job_name: 'buds-bff'
      #   kubernetes_sd_configs:
      #     - role: pod
      #   relabel_configs:
      #     - source_labels: [__meta_kubernetes_pod_label_app]
      #       action: keep
      #       regex: buds-bff
      #     - source_labels: [__meta_kubernetes_namespace]
      #       action: keep
      #       regex: pre-prod
      #     - source_labels: [__meta_kubernetes_pod_container_port_number]
      #       action: keep
      #       regex: 3000  # Adjust this to match your actual metrics port name if needed
      #   metrics_path: '/api/v1/metrics'

