apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.web.podname}}
spec:
  replicas: {{.Values.web.replicas}}
  selector:
    matchLabels:
      app: {{.Values.web.labels}}

  template:
    metadata:
      labels:
        app: {{.Values.web.labels}}
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        ports:
        - containerPort: 80
        command:
        - 'bash'
        - '-c'
        - {{.Values.web.command}}