apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.svc_pod_name}}
spec:
  selector:
    app: {{.Values.web.labels}}
  ports:
    - protocol: TCP
      port: {{.Values.service.svc_port}}
      targetPort: 80
  type: {{.Values.service.type}}
