## This secret is used in fluentd
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: efk
type: Opaque
data:
  password: cHJvZGNlcnNhaTEyMw==
  username: ZWxhc3RpYw==