apiVersion: v1
kind: Pod
metadata: 
  name: emptyvolumepod
  labels:
    env: dev

spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do hi i am from c1; sleep 10; done"]
    volumeMounts:
    - name: volume
      mountPath: /tmp/c1
  - name: c2
    image: centos
    command: ["/bin/bash", "-c", "while true; do hi i am from c2; sleep 30; done"]
    volumeMounts:
    - name: volume
      mountPath: /tmp/c2
  volumes:
  - name: volume
    emptyDir: {}