apiVersion: v1
kind: Service
metadata: 
  name: deploy-svc 
  namespace: practice
spec: 
  ports:
    - port: 80        # container port exposed
      targetPort: 80  # Pod port
  selector:
    name: webserver  # apply this service to any pods which has the specific label
  type: LoadBalancer     # specifies the service type i.e, Cluster IP or NodePort

