apiVersion: v1
kind: Service
metadata:
  #namespace: game-2048
  name: service-2048
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app-2048
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: webserversvc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: webserver
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP