apiVersion: v1
kind: Pod
metadata:
  name: linuxos
spec:
  containers:
  - name: linux
    image: ubuntu
    resources:
      requests:
        memory: "2Gi"
        cpu: "2"
      limits:
        memory: "4Gi"
        cpu: "4"
  #priorityClassName: high
