apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata: 
    name: pods-medium
    #namespace: test
  spec:
    hard:
      cpu: "4"
      memory: 16Gi
      pods: "30"
    scopeSelector:
      matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["medium"]