apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ResourceQuota
  metadata: 
    name: pods-low
    #namespace: dev
  spec:
    hard:
      cpu: "2"
      memory: 8Gi
      pods: "18"
    scopeSelector:
      matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values: ["low"]