apiVersion: v1
kind: PersistentVolume
  name: mysql-pv
  namespace: practice
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce         # ReadWriteOnce, ReadOnlyMany, ReadWriteMany, ReadWriteOncePod
  capacity: 
    storage: 2Gi
  persistentVolumeReclaimPolicy: Recycle    # Retain -> manual reclamation, Recycle -> basic scrub (rm -rf /thevolume/*), Delete -- associated storage asset such as AWS EBS, GCE PD, Azure Disk, or OpenStack Cinder volume is deleted
  storageClassName: ""
  volumeMode: Filesystem      # Kubernetes supports two volumeModes of PersistentVolumes: "Filesystem" and "Block"
  hostPath:
      path: /tmp/data/pv-1  