apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
    name: mypod
    volumeMounts:
          - name: azurefileshare
            mountPath: /app/src/Host/Files/Images/ApplicationUser
volumes:
  - name: azurefileshare
    persistentVolumeClaim:
      claimName: azurefilePVC