apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefilePVC
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: azurefilePV
  resources:
    requests:
      storage: 10Gi
