apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
spec:
  containers: 
    - name: tomcatcont
      image: tomcat:8.0
      ports:
        - name: tomcat-port
          containerPort: 7500
      imagePullPolicy: Always
      
      volumeMounts:
        - mountPath: "/var/secrets"
          name: appsecret

  volumes:
  - name: appsecret
    csi:
      driver: secrets-store.csi.x-k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: "aws-secrets"