---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-secrets-store-provider-aws
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::512154803514:role/api-token-access