apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
  namespace: practice
spec:
  containers: 
    - name: tomcatcont
      image: tomcat:8.0
      ports:
        - name: tomcat-port
          containerPort: 7500
      imagePullPolicy: Always
      env:
        - name: database_credentials
          valueFrom:
            configMapKeyRef:
              name: cmfile      # <= name of cm pod
              key: db.txt      # <= name of key of value in pod



