# ################################   MySql

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata: 
#   name: mysql-pvc
#   labels:
#     app: wordpress
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: "" 
#   volumeMode: Filesystem    
#   volumeName: mysql-pv      

# ---

################################  WP

apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: wp-pvc
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: "" 
  volumeMode: Filesystem    
  volumeName: wp-pv      