# apiVersion: v1
# kind: Secret
# metadata:
#   name: secret
# type: Opaque
# data:
#   WORDPRESS_DB_PASSWORD: UmVkaGF0MTIz
#   WORDPRESS_DB_USER: c3VuaWwK



apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: secret
  type: Opaque
  data:
    WORDPRESS_DB_PASSWORD: UmVkaGF0MTIz
    WORDPRESS_DB_USER: c3VuaWw=

