apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: practice
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy: 
    type: Recreate
  
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress:4.8-apache
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-svc
            # - name: WORDPRESS_DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: mysql-pass
            #       key: password

            - name: WORDPRESS_DB_PASSWORD
              value: password

          ports:
            - name: wordpress
              containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html

      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc

---

#################################   SVC

apiVersion: v1
kind: Service
metadata:
  name: wp-svc
  namespace: practice
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
    tier: frontend
  type: NodePort


