apiVersion: v1
kind: Pod
metadata: 
  name: selector_service
  labels:
    env: dev
spec:
  containers:
    - name: ubuntucont
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo hello sunil; sleep 5; done"]
  nodeSelector: 
    hardware: t2.micro
