apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels:
    env: dev

spec:
  containers:
    - name: apache
      image: sunilkumawat/myweb:v2
      ports:
      - name: apacheport
        containerPort: 80