apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: practice
spec:
  containers:
    - name: tomcat
      image: tomcat:8.0
      imagePullPolicy: Always
      ports:
      - name: tomcat-port
        containerPort: 7500
      env:
        - name: dbvariable
          valueFrom:
            secretKeyRef: 
              name: dbsecret
              key: db_pass
                   
        