apiVersion: v1
kind: Pod
metadata:
  name: app1
  namespace: practice
spec:
  containers:
    - name: tomcat
      image: tomcat:8.0
      imagePullPolicy: Always
      ports:
      - name: tomcat-port
        containerPort: 7500
      env:
        - name: dbuservariable
          valueFrom:
            secretKeyRef: 
              name: dbsecret1
              key: db_user
        - name: dbpassvariable
          valueFrom:
            secretKeyRef: 
              name: dbsecret1
              key: db_pass
                   
        