apiVersion: apps/v1
kind: Deployment
metadata:
   name: webapache
spec:
   replicas: 1
   selector:
    matchLabels:
     name: deployment
   template:
     metadata:
       name: testpod8
       labels:
         name: deployment
     spec:
      containers:
        - name: web
          image: httpd
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "100Mi"
              cpu: "125m"
            limits:
              memory: "250Mi"
              cpu: "250m"
          # resources:
          #   limits:
          #     cpu: 500m
          #   requests:
          #     cpu: 200m