apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webapache
  minReplicas: 1
  maxReplicas: 6
  #targetCPUUtilizationPercentage: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 40
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 900
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 120    
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120 # (i.e., scale down one pod every 10 min)
       

  # behavior	<Object>
  #        scaleDown	<Object>
  #           policies	<[]Object>
  #              periodSeconds	<integer>
  #              type	<string>
  #              value	<integer>
  #           selectPolicy	<string>
  #           stabilizationWindowSeconds	<integer>
  #        scaleUp	<Object>
  #           policies	<[]Object>
  #              periodSeconds	<integer>
  #              type	<string>
  #              value	<integer>
  #           selectPolicy	<string>
  #           stabilizationWindowSeconds	<integer>


status:
  observedGeneration: 1
  lastScaleTime:
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
