apiVersion: v1
kind: ReplicationController
metadata:
  name: myreplica
spec:
  replicas: 2
  selector:
    name: sunil
  template:
    metadata:
      name: replicaPod
      labels:
        name: sunil

    spec:
      containers:
        - name: ubuntucontainer
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo hello sunil; sleep 5; done"]
