# konga-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga
  namespace: kong-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konga
  template:
    metadata:
      labels:
        app: konga
    spec:
      containers:
        - name: konga
          image: pantsel/konga:latest
          ports:
            - containerPort: 1337
          env: 
          - name: KONG_DATABASE
            value: konga
          - name: KONG_PG_HOST
            value: konga.c8jpdru8xvpc.us-east-1.rds.amazonaws.com
          - name: KONG_PG_USER
            value: konga
          - name: KONG_PG_PASSWORD
            value: Redhat123
          - name: KONG_PG_PORT
            value: 5432
