# kong-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: kong-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:latest
          ports:
            - containerPort: 8000
            - containerPort: 8443
            - containerPort: 8001
            - containerPort: 8444
          env: 
          - name: KONG_DATABASE
            value: konga
          - name: KONG_PG_HOST
            value: konga.c8jpdru8xvpc.us-east-1.rds.amazonaws.com
          - name: KONG_PG_USER
            value: konga
          - name: KONG_PG_PASSWORD
            value: Redhat123
          - name: KONG_PG_PORT
            value: 5432
