# konga-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: konga
  namespace: kong-system
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 1337
  selector:
    app: konga
