apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: developer
  name: developer-role
rules:
- apiGroups: ["", "extensions", "apps"]                                    # <= "" indicates the core API group
  resources: ["deployments", "replicasets", "pods", "namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]   # <= and also use ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: developer
subjects:
- kind: User
  name: shyam
  apiGroup: ""
roleRef:
  kind: Role
  name: developer-role
  apiGroup: ""