# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: dinosaur
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: game-2048
  name: dinosaur
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dinosaur
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dinosaur
    spec:
      containers:
      - image: sunilkumawat/dinosaur:v3
        imagePullPolicy: Always
        name: dinosaur
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: game-2048
  name: dinosaur
spec:
  ports:
    - port: 80
      targetPort: 3000 
      protocol: TCP
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dinosaur
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   namespace: game-2048
#   name: dinosaur
#   annotations:
#     kubernetes.io/ingress.class: 'nginx'
# spec:
#   ingressClassName: 'nginx'
#   rules:
#     - host: 'gke.myeasydevops.xyz'
#       http:
#         paths:
#         - path: /dinosaur
#           pathType: Prefix
#           backend:
#             service:
#               name: dinosaur
#               port:
#                 number: 80
