apiVersion: v1
kind: Pod
metadata: 
  name: firstpod
  labels: 
    env: dev

spec: 
  initContainers:
    - name: helper
      image: bitnami/git
      command: 
        - git 
        - clone
        - https://github.com/SUNILKUMARKUMAWAT371/samplerepo.git
        - /tmp
      volumeMounts:
        - name: scratch
          mountPath: "/tmp"
      
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - name: http-container
          containerPort: 80
      volumeMounts:
        - name: scratch
          mountPath: "/usr/share/nginx/html"
  
  volumes:
    - name: scratch
      emptyDir: {}

---

apiVersion: v1
kind: Service
metadata: 
  name: pod-svc
spec:
  selector: 
    env: dev
  ports: 
    - protocol: TCP
      port: 80
      targetport: 80
  
  

         


