apiVersion: v1
kind: Pod
metadata: 
  - name: volumePod
    label:
      - env: dev

spec: 
  containers:
    - name: apache
      image: httpd:latest
      ports:
        - name: http-port
          containerPort: 80
      volumeMounts:
        - name: webpageVolume
          mountPath: /var/www/html

  volumes:
    - name: webpageVolume


