apiVersion: v1
kind: Pod
metadata:
  name: tomcatpod
  namespace: practice
spec:
  containers: 
    - name: tomcatcont
      image: tomcat:8.0
      ports:
        - name: tomcat-port
          containerPort: 7500
      imagePullPolicy: Always
      env:
        - name: database_user
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: db_user
        - name: database_name
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: db_name   
        - name: database_env
          valueFrom:
            configMapKeyRef:
              name: cm1
              key: db_env



